/**
 * Test fixture configuration for polaroid extraction tests.
 * 
 * NOTE: These paths are hardcoded to local filesystem locations and are NOT
 * committed to git. Each developer should update these paths to point to their
 * own test images.
 */

export interface TestImage {
  /** Filename of the test image */
  filename: string;
  /** Expected number of polaroids to extract from this image */
  expectedCount: number;
  /** 
   * Optional baseline perceptual hashes for the extracted polaroids.
   * These are generated by running `pnpm run test:baselines` when the
   * extraction algorithm is known to be working correctly.
   */
  baselineHashes?: string[];
}

export interface TestFixture {
  /** Absolute path to the folder containing test images */
  folder: string;
  /** List of test images in this folder */
  images: TestImage[];
}

/**
 * Test fixtures configuration.
 * 
 * Add your test folders and images here. Each image should specify:
 * - filename: The name of the image file
 * - expectedCount: How many polaroids should be extracted
 * - baselineHashes: (optional) pHash values for visual comparison
 */
export const testFixtures: TestFixture[] = [
  {
    folder: '/Users/lukemcgartland/Pictures/macki/raw',
    images: [
      { filename: 'lux_snacks_1.png', expectedCount: 4 },
      { filename: 'lux_snacks_1 1.png', expectedCount: 4 },
      { filename: 'lux_snacks_1 2.png', expectedCount: 4 },
      { filename: 'lux_snacks_1 3.png', expectedCount: 4 },
    ]
  }
];

/**
 * Hamming distance threshold for perceptual hash comparison.
 * Images with a distance less than this value are considered visually similar.
 * 
 * - 0: Identical images
 * - 1-10: Minor differences (compression, slight color shifts)
 * - 10-20: Noticeable but acceptable differences
 * - >20: Significant differences, likely a regression
 */
export const PHASH_SIMILARITY_THRESHOLD = 10;

